# Generated by Django 6.0.2 on 2026-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_CMB_ITEM',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CMB_TYPE', models.CharField(max_length=128)),
                ('CMB_VALUE', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'M_CMB_ITEM',
            },
        ),
        migrations.CreateModel(
            name='M_SHIKAISHI',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('SHIKAI_NAME', models.CharField(max_length=128)),
                ('YAKUSHOKU', models.IntegerField()),
            ],
            options={
                'db_table': 'M_SHIKAISHI',
            },
        ),
        migrations.CreateModel(
            name='T_JUSHINREKI',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('KANZYA_ID', models.IntegerField()),
                ('SHIKAISHI_ID', models.IntegerField()),
                ('JUSHINBI', models.DateField()),
                ('JUSHIN_RIYUU', models.TextField()),
                ('RYOUKIN_ZENGAKU', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RYOUKIN_KANZYAFUTAN', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UPDATE_DATE', models.DateTimeField(auto_now=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'T_JUSHINREKI',
            },
        ),
        migrations.CreateModel(
            name='T_KANZYA',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('KANZYA_NAME', models.CharField(max_length=128)),
                ('SEINENGAPPI', models.DateField()),
                ('EMAIL_ADDRESS', models.EmailField(max_length=254)),
                ('RAIIN_RIYUU', models.IntegerField()),
                ('RAIIN_RIYUU_SONOTA', models.TextField()),
                ('ZYOUHOU_MOTO', models.IntegerField()),
                ('ZYOUHOU_MOTO_SONOTA', models.TextField()),
                ('TANTOU_SHIKAISHI_ID', models.IntegerField()),
                ('SONOTA_YOUBOU', models.TextField()),
                ('UPDATE_DATE', models.DateTimeField(auto_now=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'T_KANZYA',
            },
        ),
        migrations.CreateModel(
            name='T_YOYAKU',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('KANZYA_ID', models.IntegerField()),
                ('YOYAKUBI', models.DateTimeField()),
                ('UKETSUKEBI', models.DateTimeField()),
                ('BIKOU', models.TextField()),
                ('UPDATE_DATE', models.DateTimeField(auto_now=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'T_YOYAKU',
            },
        ),
    ]
