# Generated by Django 6.0.2 on 2026-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoyakuKanri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_kanzya',
            name='RAIIN_RIYUU_SONOTA',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='SONOTA_YOUBOU',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='ZYOUHOU_MOTO_SONOTA',
            field=models.TextField(null=True, blank=True),
        ),
    ]
