# Generated by Django 6.0.2 on 2026-02-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoyakuKanri', '0002_alter_t_kanzya_raiin_riyuu_sonota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_kanzya',
            name='RAIIN_RIYUU_SONOTA',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='SONOTA_YOUBOU',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='ZYOUHOU_MOTO_SONOTA',
            field=models.TextField(blank=True, null=True),
        ),
    ]
