# Generated by Django 6.0.2 on 2026-02-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoyakuKanri', '0003_alter_t_kanzya_raiin_riyuu_sonota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_yoyaku',
            name='BIKOU',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_yoyaku',
            name='UKETSUKEBI',
            field=models.DateTimeField(null=True),
        ),
    ]
