# Generated by Django 6.0.2 on 2026-02-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoyakuKanri', '0004_alter_t_yoyaku_bikou_alter_t_yoyaku_uketsukebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_kanzya',
            name='UKETSUKEBI',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='t_kanzya',
            name='ZIKAI_YOYAKUBI',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='t_yoyaku',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
