# Generated by Django 6.0.2 on 2026-02-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoyakuKanri', '0005_t_kanzya_uketsukebi_t_kanzya_zikai_yoyakubi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_yoyaku',
            name='BIKOU',
        ),
        migrations.AddField(
            model_name='t_kanzya',
            name='BIKOU',
            field=models.TextField(blank=True, null=True),
        ),
    ]
