# Generated by Django 6.0.2 on 2026-02-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoyakuKanri', '0006_remove_t_yoyaku_bikou_t_kanzya_bikou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_kanzya',
            name='RAIIN_RIYUU',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='TANTOU_SHIKAISHI_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='ZYOUHOU_MOTO',
            field=models.TextField(blank=True, null=True),
        ),
    ]
