# Generated by Django 6.0.1 on 2026-02-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoyakuKanri', '0007_alter_t_kanzya_raiin_riyuu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_kanzya',
            name='RAIIN_RIYUU',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='UKETSUKEBI',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='ZIKAI_YOYAKUBI',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='ZYOUHOU_MOTO',
            field=models.TextField(blank=True, null=True),
        ),
    ]
