# Generated by Django 6.0.1 on 2026-03-07 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoyakuKanri', '0008_alter_t_kanzya_raiin_riyuu_alter_t_kanzya_uketsukebi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_kanzya',
            name='TANTOU_SHIKAISHI_ID',
        ),
        migrations.AddField(
            model_name='t_jushinreki',
            name='JUSHIN_TITLE',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='t_jushinreki',
            name='SHOCHI_NAIYOU',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_kanzya',
            name='SHIKAISHI',
            field=models.ForeignKey(blank=True, db_column='TANTOU_SHIKAISHI_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='YoyakuKanri.m_shikaishi'),
        ),
        migrations.AlterField(
            model_name='m_shikaishi',
            name='YAKUSHOKU',
            field=models.IntegerField(choices=[(1, '歯科医師'), (2, '歯科助手'), (3, '技工士'), (4, '受付')]),
        ),
        migrations.AlterField(
            model_name='t_jushinreki',
            name='JUSHIN_RIYUU',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='RAIIN_RIYUU',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_kanzya',
            name='ZYOUHOU_MOTO',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
