# Generated by Django 6.0.1 on 2026-03-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoyakuKanri', '0009_remove_t_kanzya_tantou_shikaishi_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_jushinreki',
            name='SHIKAISHI_ID',
        ),
        migrations.AddField(
            model_name='t_jushinreki',
            name='SHIKAISHI',
            field=models.ForeignKey(blank=True, db_column='SHIKAISHI_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='YoyakuKanri.m_shikaishi'),
        ),
        migrations.AlterField(
            model_name='t_jushinreki',
            name='RYOUKIN_KANZYAFUTAN',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_jushinreki',
            name='RYOUKIN_ZENGAKU',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
